import type { Metadata } from 'next'

import { Inter_Tight, Geist_Mono } from 'next/font/google'
import './globals.css'

import { ThemeProvider } from '@/components/others/theme-provider'

const interTight = Inter_Tight({ variable: '--font-inter-tight', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ZEUS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${interTight.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}

